# Generated by Django 4.1.6 on 2023-03-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_tracker', '0002_alter_assignment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
